version: "3.8"
services:
  service_1:
    image: aalphonso/qa2:name-generator-front
    deploy:
      replicas: 3
    build: ./service_1
    container_name: service1
    networks:
      - example-net
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
  service_2:
    image:  aalphonso/qa2:name-generator-prefix
    deploy:
      replicas: 3
    build: ./service_2
    container_name: service2
    ports:
      - target: 5001
        published: 5001
        protocol: tcp
    networks:
      - example-net
  service_3:
    image:  aalphonso/qa2:name-generator-suffix
    deploy:
      replicas: 3
    build: ./service_3
    container_name: service3
    ports:
      - target: 5002
        published: 5002
        protocol: tcp
    networks:
      - example-net
  service_4:
    image:  aalphonso/qa2:name-generator-genre
    deploy:
      replicas: 3
    build: ./service_4
    container_name: service4
    ports:
      - target: 5003
        published: 5003
        protocol: tcp
    networks:
      - example-net    
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - example-net
    volumes:
      - type: bind
        source: /home/Kaobi/docker-demos/prize-generator/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - target: 80
        published: 80
        protocol: tcp
    depends_on:
      - service_1
networks:
  example-net:
    driver: overlay
    attachable: true