version: "3.8"
services:
  service_1:
    image: name-generator-front:v1
    build: ./service_1
    container_name: service1
    networks:
      - example-net
  service_2:
    image: name-generator-chars:v1
    build: ./service_2
    container_name: service2
    networks:
      - example-net
  service_3:
    image: name-generator-suffix:v1
    build: ./service_3
    container_name: service3
    networks:
      - example-net
  service_4:
    image: name-generator-prize:v1
    build: ./service_4
    container_name: service4
    networks:
      - example-net    
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - example-net
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - target: 80
        published: 80
        protocol: tcp
    depends_on:
      - service_1
networks:
  example-net: